require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.3'

target 'ReactNativeBoilerPlaceHermes' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  #pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'ReactNativeBoilerPlaceHermesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  # Detect AppCenter CI build
  IS_CI = ENV['APPCENTER_BUILD_ID']
  # ...
  if not IS_CI
    use_flipper!()
  end
  # ...
  post_install do |installer|
      if not IS_CI
        use_flipper!
      end
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end
