const AppColors = {
  welcome_green: "#e5fcfb",
  welcomePink: "#ffb3b3",
  green: '#2898A4',
  green1: '#B2CCCF',
  lightestGreen: "#EAF8FA",
  black2: '#A8A8A8',
  white: '#ffffff',
  lightestWhite: "#ECECEC",
  transparent: 'transparent',
  gray: '#FAFAFA',
  gray1: '#F2F2F2',
  black: 'black',
  black1: '#545454',
  black3: '#878787',
  lightestBlue: "#EBEFFA",
  lightGreen: '#E0EEF0',
  grayBorder: '#E1E1E1',
  titlecolor: '#545454',
  red: '#E70000',
  red2 : "#FF6666",
  pink: '#FF7372',
  lightPink: '#FFE7E7',
  darkGray: '#A8A8A8',
  blue1: '#C2D4FF',
  blue2: '#99E6FF',
  newBlue: '#5B7ED7',
  purple: '#ADBFEB',
  green2: '#ADE5EB',
  lightOrange: '#FCE2AF',
  lightMediumGreen: "#55C0CC",
  yellow: "#F8B636",
  newYellow: "#FEDFCD",
  lightYellow: "#FCDC9C",
  whiteBase: "#E5E5E5",
  blackgray: "#C4C4C4",
  smallShadow: {
    shadowColor: this.gray,
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 1.1,
  },
  bigShadow: {
    shadowColor: this.gray,
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 5,
  },
  shadowStyles: {
    shadowColor: '#F2F2F2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 2,
  },
  noShadow: {
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
};

export const ColorList = [
  "#FFE7E7",
  "#C2D4FF",
  "#FCE2AF",
  "#99E6FF"
]
export const ColorList2 = [
  "#C2D4FF",
  "#FCE2AF",
  "#99E6FF"
]
export default AppColors;
